version: "3.8"

services:
    tzbox:
        image: tqtezos/flextesa:20210602
        command: ["granabox", "start"]
        ports:
            - "20000:20000"
        environment:
           - TEZOS_CLIENT_UNSAFE_DISABLE_DISCLAIMER=yes
           - block_time=2
    nats:
        image: nats:latest
        command: ["-js"]
        ports:
            - "4222:4222"
            - "6222:6222"
            - "8222:8222"
    authorization-service:
        image: jwalab/authorization-service:0.0.4
        ports:
            - "8999:8999"
        environment:
            - TOKEN_ISSUER=authorization-service
        restart: always
    airlock:
        image: jwalab/airlock:0.0.8
        ports:
            - "8000:8000"
        restart: always
        environment:
            - NATS_URL=nats://nats:4222
            - SECURE=false
            - AUTH_URL=authorization-service:8999
            - AUTH_PROTOCOL=http
        depends_on: 
            - nats
            - authorization-service
    tzindex:
        image: blockwatch/tzindex:v9.1-rc2
        # https://github.com/blockwatch-cc/tzindex/issues/13
        command: ["sh", "-c", "sleep 10 && tzindex run"]
        ports:
            - "8002:8002"
        user: root
        environment:
            - TZ_RPC_HOST=tzbox
            - TZ_RPC_PORT=20000
            - TZ_SERVER_ADDR=0.0.0.0
            - TZ_SERVER_PORT=8002
            - TZ_SERVER_CORS_ENABLE=true
            - TZ_DATABASE_PATH=/data/index
            - TZ_SNAPSHOT_PATH=/data/snapshots
        restart: always
        depends_on:
            - tzbox
    tzstats:
        image: blockwatch/tzstats
        ports:
            - "8001:8001"
        environment:
            - TZSTATS_API_URL=http://localhost:8002
            - SV_HEADERS_Content-Security-Policy=default-src 'self' 'unsafe-inline' http://localhost:*;
            - SV_SERVER_PORT=8001
        restart: always
        depends_on:
            - tzindex
    postgres:
        image: postgres
        environment:
            - POSTGRES_USER=jwa
            - POSTGRES_PASSWORD=jwalab
            - POSTGRES_DB=item
        ports:
            - "5432:5432"
    item-service:
        image: jwalab/item-service:0.0.1
        entrypoint: [
            "sh", "-c", 
            "npm run seed-db && sleep 10 && export WAREHOUSE_CONTRACT_ADDRESS=$$(npm run deploy-warehouse --silent) && npm run start"
        ]
        environment:
            - SERVICE_NAME=item-service
            - NATS_URL=nats://nats:4222
            - TEZOS_RPC_URI=http://tzbox:20000
            - TEZOS_SECRET_KEY=edsk3QoqBuvdamxouPhin7swCvkQNgq4jP5KZPbwWNnwdZpSpJiEbq
            - TEZOS_PUBLIC_KEY_HASH=tz1VSUr8wwNhLAzempoch5d6hLRiTh8Cjcjb
            - LOGGING_FORMAT=full
            - PGSQL_HOST=postgres
            - PGSQL_USER=jwa
            - PGSQL_PASSWORD=jwalab
            - PGSQL_DATABASE=item
        restart: always
        depends_on:
            - postgres
            - nats
            - tzbox
    tezos-work-queue:
        image: jwalab/tezos-work-queue:0.0.1
        entrypoint: [
            "sh",  "-c",
            "sleep 10 && npm run start"
        ]
        environment:
            - NATS_URL=nats://nats:4222
            - TEZOS_RPC_URI=http://tzbox:20000
            - TEZOS_SECRET_KEY=edsk3QoqBuvdamxouPhin7swCvkQNgq4jP5KZPbwWNnwdZpSpJiEbq
            - LOGGING_FORMAT=full
        restart: always
        depends_on:
            - item-service
            - nats
            - tzbox
    swagger-ui:
        image: swaggerapi/swagger-ui
        ports:
            - "80:8080"
        environment:
            API_URL: http://localhost:8000/docs
