version: "3.8"

services:
    carthagebox:
        image: tqtezos/flextesa:20200925
        command: ["carthagebox", "start"]
        ports:
            - "20000:20000"
        environment:
           - TEZOS_CLIENT_UNSAFE_DISABLE_DISCLAIMER=yes
    nats:
        image: nats:latest
        command: []
        ports:
            - "4222:4222"
            - "6222:6222"
            - "8222:8222"
    airlock:
        image: jwalab/airlock:latest
        ports:
            - "8000:8000"
        restart: always
        environment:
            - NATS_URL=nats://nats:4222
        depends_on: 
            - nats
    tzindex:
        image: blockwatch/tzindex
        # https://github.com/blockwatch-cc/tzindex/issues/13
        command: ["sh", "-c", "sleep 10 && tzindex run"]
        ports:
            - "8002:8002"
        environment:
            - TZ_RPC_HOST=carthagebox
            - TZ_RPC_PORT=20000
            - TZ_SERVER_ADDR=0.0.0.0
            - TZ_SERVER_PORT=8002
            - TZ_SERVER_CORS_ENABLE=true
            - TZ_DATABASE_PATH=/data/index
            - TZ_SNAPSHOT_PATH=/data/snapshots
        restart: always
        depends_on:
            - carthagebox
    tzstats:
        image: blockwatch/tzstats
        ports:
            - "8001:8001"
        environment:
            - TZSTATS_API_URL=http://localhost:8002
            - SV_HEADERS_Content-Security-Policy=default-src 'self' 'unsafe-inline' http://localhost:*;
            - SV_SERVER_PORT=8001
        restart: always
        depends_on:
            - tzindex
    tokenization-service:
        image: jwalab/tokenization-service
        environment: 
            - TEZOS_RPC_URI=http://carthagebox:20000
            - WAREHOUSE_TEZOS_SECRET_KEY=edsk3QoqBuvdamxouPhin7swCvkQNgq4jP5KZPbwWNnwdZpSpJiEbq
            - WAREHOUSE_TEZOS_PUBLIC_KEY_HASH=tz1VSUr8wwNhLAzempoch5d6hLRiTh8Cjcjb
            - WAREHOUSE_CONTRACT_ADDRESS=${WAREHOUSE_CONTRACT_ADDRESS}
            - NATS_URL=nats://nats:4222
        restart: always
        depends_on: 
            - carthagebox
            - nats
    item-store:
        image: jwalab/item-store
        environment:
            - NATS_URL=nats://nats:4222
            - ELASTICSEARCH_URI=http://elasticsearch:9200
            - ELASTICSEARCH_INDEX_NAME=jwa_item_store
        restart: always
        depends_on: 
            - elasticsearch
            - nats
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
        environment:
            - discovery.type=single-node
        ports:
            - 9200:9200
            - 9300:9300
    kibana:
        image: docker.elastic.co/kibana/kibana:7.9.2
        ports:
            - "5601:5601"
    swagger-ui:
        image: swaggerapi/swagger-ui
        ports:
            - "80:8080"
        environment:
            API_URL: http://localhost:8000/docs
